# Form implementation generated from reading ui file 'c:\Users\vladk\OneDrive\Рабочий стол\work\code\4zadanie\main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EscapingButtonWidget(object):
    def setupUi(self, EscapingButtonWidget):
        EscapingButtonWidget.setObjectName("EscapingButtonWidget")
        EscapingButtonWidget.resize(600, 400)
        self.escapeButton = QtWidgets.QPushButton(parent=EscapingButtonWidget)
        self.escapeButton.setGeometry(QtCore.QRect(250, 180, 100, 40))
        self.escapeButton.setObjectName("escapeButton")

        self.retranslateUi(EscapingButtonWidget)
        QtCore.QMetaObject.connectSlotsByName(EscapingButtonWidget)

    def retranslateUi(self, EscapingButtonWidget):
        _translate = QtCore.QCoreApplication.translate
        EscapingButtonWidget.setWindowTitle(_translate("EscapingButtonWidget", "Убегающая кнопка"))
        self.escapeButton.setText(_translate("EscapingButtonWidget", "Поймай меня!"))
