# Form implementation generated from reading ui file 'c:\Users\vladk\OneDrive\Рабочий стол\work\code\5zadanie\main2.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UfoWidget(object):
    def setupUi(self, UfoWidget):
        UfoWidget.setObjectName("UfoWidget")
        UfoWidget.resize(800, 600)

        self.retranslateUi(UfoWidget)
        QtCore.QMetaObject.connectSlotsByName(UfoWidget)

    def retranslateUi(self, UfoWidget):
        _translate = QtCore.QCoreApplication.translate
        UfoWidget.setWindowTitle(_translate("UfoWidget", "Управление НЛО"))
