# Form implementation generated from reading ui file 'c:\Users\vladk\OneDrive\Рабочий стол\work\code\6zadanie\auth.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthDialog(object):
    def setupUi(self, AuthDialog):
        AuthDialog.setObjectName("AuthDialog")
        AuthDialog.resize(360, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(AuthDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hLayoutLogin = QtWidgets.QHBoxLayout()
        self.hLayoutLogin.setObjectName("hLayoutLogin")
        self.label_login = QtWidgets.QLabel(parent=AuthDialog)
        self.label_login.setObjectName("label_login")
        self.hLayoutLogin.addWidget(self.label_login)
        self.login_edit = QtWidgets.QLineEdit(parent=AuthDialog)
        self.login_edit.setObjectName("login_edit")
        self.hLayoutLogin.addWidget(self.login_edit)
        self.verticalLayout.addLayout(self.hLayoutLogin)
        self.hLayoutPwd = QtWidgets.QHBoxLayout()
        self.hLayoutPwd.setObjectName("hLayoutPwd")
        self.label_pwd = QtWidgets.QLabel(parent=AuthDialog)
        self.label_pwd.setObjectName("label_pwd")
        self.hLayoutPwd.addWidget(self.label_pwd)
        self.pwd_edit = QtWidgets.QLineEdit(parent=AuthDialog)
        self.pwd_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pwd_edit.setObjectName("pwd_edit")
        self.hLayoutPwd.addWidget(self.pwd_edit)
        self.verticalLayout.addLayout(self.hLayoutPwd)
        self.hLayoutButtons = QtWidgets.QHBoxLayout()
        self.hLayoutButtons.setObjectName("hLayoutButtons")
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hLayoutButtons.addItem(spacerItem)
        self.login_btn = QtWidgets.QPushButton(parent=AuthDialog)
        self.login_btn.setObjectName("login_btn")
        self.hLayoutButtons.addWidget(self.login_btn)
        self.register_btn = QtWidgets.QPushButton(parent=AuthDialog)
        self.register_btn.setObjectName("register_btn")
        self.hLayoutButtons.addWidget(self.register_btn)
        self.verticalLayout.addLayout(self.hLayoutButtons)

        self.retranslateUi(AuthDialog)
        QtCore.QMetaObject.connectSlotsByName(AuthDialog)

    def retranslateUi(self, AuthDialog):
        _translate = QtCore.QCoreApplication.translate
        AuthDialog.setWindowTitle(_translate("AuthDialog", "Вход / Регистрация"))
        self.label_login.setText(_translate("AuthDialog", "Логин:"))
        self.label_pwd.setText(_translate("AuthDialog", "Пароль:"))
        self.login_btn.setText(_translate("AuthDialog", "Войти"))
        self.register_btn.setText(_translate("AuthDialog", "Зарегистрироваться"))
