# Form implementation generated from reading ui file 'c:\Users\vladk\OneDrive\Рабочий стол\work\code\6zadanie\book.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BookDialog(object):
    def setupUi(self, BookDialog):
        BookDialog.setObjectName("BookDialog")
        BookDialog.resize(420, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(BookDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_title = QtWidgets.QLabel(parent=BookDialog)
        self.label_title.setObjectName("label_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_title)
        self.title_edit = QtWidgets.QLineEdit(parent=BookDialog)
        self.title_edit.setObjectName("title_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.title_edit)
        self.label_author = QtWidgets.QLabel(parent=BookDialog)
        self.label_author.setObjectName("label_author")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_author)
        self.author_edit = QtWidgets.QLineEdit(parent=BookDialog)
        self.author_edit.setObjectName("author_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.author_edit)
        self.label_year = QtWidgets.QLabel(parent=BookDialog)
        self.label_year.setObjectName("label_year")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_year)
        self.year_spin = QtWidgets.QSpinBox(parent=BookDialog)
        self.year_spin.setMinimum(1000)
        self.year_spin.setMaximum(3000)
        self.year_spin.setObjectName("year_spin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.year_spin)
        self.label_genre = QtWidgets.QLabel(parent=BookDialog)
        self.label_genre.setObjectName("label_genre")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_genre)
        self.genre_combo = QtWidgets.QComboBox(parent=BookDialog)
        self.genre_combo.setObjectName("genre_combo")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.genre_combo)
        self.label_image = QtWidgets.QLabel(parent=BookDialog)
        self.label_image.setObjectName("label_image")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_image)
        self.hImage = QtWidgets.QHBoxLayout()
        self.hImage.setObjectName("hImage")
        self.image_name_label = QtWidgets.QLabel(parent=BookDialog)
        self.image_name_label.setObjectName("image_name_label")
        self.hImage.addWidget(self.image_name_label)
        self.choose_btn = QtWidgets.QPushButton(parent=BookDialog)
        self.choose_btn.setObjectName("choose_btn")
        self.hImage.addWidget(self.choose_btn)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.hImage)
        self.verticalLayout.addLayout(self.formLayout)
        self.hButtons = QtWidgets.QHBoxLayout()
        self.hButtons.setObjectName("hButtons")
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hButtons.addItem(spacerItem)
        self.ok_btn = QtWidgets.QPushButton(parent=BookDialog)
        self.ok_btn.setObjectName("ok_btn")
        self.hButtons.addWidget(self.ok_btn)
        self.cancel_btn = QtWidgets.QPushButton(parent=BookDialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.hButtons.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.hButtons)

        self.retranslateUi(BookDialog)
        QtCore.QMetaObject.connectSlotsByName(BookDialog)

    def retranslateUi(self, BookDialog):
        _translate = QtCore.QCoreApplication.translate
        BookDialog.setWindowTitle(_translate("BookDialog", "Книга"))
        self.label_title.setText(_translate("BookDialog", "Название:"))
        self.label_author.setText(_translate("BookDialog", "Автор:"))
        self.label_year.setText(_translate("BookDialog", "Год:"))
        self.label_genre.setText(_translate("BookDialog", "Жанр:"))
        self.label_image.setText(_translate("BookDialog", "Обложка:"))
        self.image_name_label.setText(_translate("BookDialog", "(не выбрано)"))
        self.choose_btn.setText(_translate("BookDialog", "Выбрать..."))
        self.ok_btn.setText(_translate("BookDialog", "OK"))
        self.cancel_btn.setText(_translate("BookDialog", "Отмена"))
